<?php
class JConfig {
	public $offline = false;
	public $offline_message = 'Este site está fora do ar para manutenção.<br />Por favor, verifique novamente em breve.';
	public $display_offline_message = 1;
	public $offline_image = '';
	public $sitename = 'Guideway LMS - O caminho simples para o seu curso online.';
	public $editor = 'tinymce';
	public $captcha = '0';
	public $list_limit = 20;
	public $access = 1;
	public $debug = 1;
	public $debug_lang = false;
	public $debug_lang_const = true;
	public $dbtype = 'mysqli';
	public $host = '127.0.0.1'; // Pode ser que o valor aqui seja 'localhost'
	public $user = 'root'; // Coloque aqui o nome do usuário do banco de dados
	public $password = 'root'; // Coloque aqui a senha do banco de dados us35#w3(b)%
	public $db = 'guidewaylms'; // Coloque aqui o nome do banco de dados
	public $dbprefix = 'bak_lepgs_';
	public $dbencryption = 0;
	public $dbsslverifyservercert = false;
	public $dbsslkey = '';
	public $dbsslcert = '';
	public $dbsslca = '';
	public $dbsslcipher = '';
	public $force_ssl = 0;
	public $live_site = 'http://127.0.0.1:8082/';
	public $secret = '72fd5fJcHf67wh';
	public $gzip = false;
	public $error_reporting = 'maximum';
	public $helpurl = 'https://help.joomla.org/proxy?keyref=Help{major}{minor}:{keyref}&lang={langcode}';
	public $offset = 'America/Sao_Paulo';
	public $mailonline = true;
	public $mailer = 'smtp';
	public $mailfrom = 'xxxxx@gmail.com'; // Coloque aqui seu email do gmail
	public $fromname = 'Guideway LMS';
	public $sendmail = '/usr/sbin/sendmail';
	public $smtpauth = true;
	public $smtpuser = 'xxxxx@gmail.com'; // Coloque aqui seu email do gmail
	public $smtppass = 'xxxxx'; // Crie a senha de app no seu gmail (nao a senha normal) e coloque aqui para uso de envio de email
	public $smtphost = 'smtp.gmail.com';
	public $smtpsecure = 'tls';
	public $smtpport = 587;
	public $caching = 0;
	public $cache_handler = 'file';
	public $cachetime = 15;
	public $cache_platformprefix = false;
	public $MetaDesc = '';
	public $MetaAuthor = true;
	public $MetaVersion = false;
	public $robots = '';
	public $sef = '0';
	public $sef_rewrite = '0';
	public $sef_suffix = false;
	public $unicodeslugs = false;
	public $feed_limit = 10;
	public $feed_email = 'none';
	public $log_path = '/home/es55/guidewaylms/administrator/logs'; // Verifique se este caminho está correto conforme seu ambiente local
	public $tmp_path = '/home/es55/guidewaylms/tmp'; // Verifique se este caminho está correto conforme seu ambiente local
	public $lifetime = 9999;
	public $session_handler = 'database';
	public $shared_session = false;
	public $session_metadata = true;
	public $memcached_persist = true;
	public $memcached_compress = false;
	public $memcached_server_host = 'localhost';
	public $memcached_server_port = 11211;
	public $redis_persist = true;
	public $redis_server_host = 'localhost';
	public $redis_server_port = 6379;
	public $redis_server_db = 0;
	public $cors = false;
	public $cors_allow_origin = '*';
	public $cors_allow_headers = 'Content-Type,X-Joomla-Token';
	public $cors_allow_methods = '';
	public $behind_loadbalancer = false;
	public $proxy_enable = false;
	public $proxy_host = '';
	public $proxy_port = '';
	public $proxy_user = '';
	public $massmailoff = false;
	public $replyto = '';
	public $replytoname = '';
	public $MetaRights = '';
	public $sitename_pagetitles = 1;
	public $session_filesystem_path = '';
	public $session_memcached_server_host = 'localhost';
	public $session_memcached_server_port = 11211;
	public $session_redis_persist = 1;
	public $session_redis_server_host = 'localhost';
	public $session_redis_server_port = 6379;
	public $session_redis_server_db = 0;
	public $session_metadata_for_guest = true;
	public $frontediting = 1;
	public $log_everything = 0;
	public $log_deprecated = 0;
	public $log_priorities = array('0' => 'all');
	public $log_categories = '';
	public $log_category_mode = 0;
	public $cookie_domain = '';
	public $cookie_path = '';
	public $asset_id = '1';
	public $redis_server_auth = '';
	public $session_redis_server_auth = '';
}