# .github/workflows/deploy.yml
name: Deploy to HostGator

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código do repositório
        uses: actions/checkout@v4

      - name: Configura o ambiente SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.HOSTGATOR_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          cat << EOF > ~/.ssh/config
          Host production_server
            HostName ${{ secrets.HOSTGATOR_HOST }}
            User ${{ secrets.HOSTGATOR_USERNAME }}
            Port ${{ secrets.HOSTGATOR_PORT }}
            IdentityFile ~/.ssh/deploy_key
            IdentitiesOnly yes
            StrictHostKeyChecking no
            PreferredAuthentications publickey
          EOF

      - name: Deploy com rsync
        run: |
          rsync -avz --delete \
            --exclude='/.git/' \
            --exclude='/.github/' \
            --exclude='/node_modules/' \
            --exclude='/cache/' \
            --exclude='/administrator/cache/' \
            --exclude='/administrator/logs/' \
            --exclude='/tmp/' \
            --exclude='/.vscode/' \
            --exclude='/configuration.php' \
            --exclude='/.htaccess' \
            --exclude='/composer.json' \
            --exclude='/composer.lock' \
            --exclude='/package-lock.json' \
            --exclude='/package.json' \
            --exclude='/.gitignore' \
            --exclude='.DS_Store' \
            ./ production_server:${{ secrets.HOSTGATOR_DESTINATION_PATH }}